import { Gym } from "./types";

export const Gyms: Gym[] = [
  {
    id: "gym_1",
    ownerId: "user_1",
    name: "Iron Haven Fitness",
    logoUrl: "https://example.com/logo1.jpg",
    description:
      "A gym that offers a variety of fitness classes and equipment.",
    location: {
      street: "12A Glover Road",
      city: "Ikoyi",
      landmark: "Near Ikoyi International Airport",
      address: "12A Glover Road, Ikoyi, Lagos",
      country: "Nigeria",
      state: "Lagos",
      postalCode: "101233",
      geoData: {
        lat: 6.4531,
        lng: 3.3922,
      },
    },
    contact: {
      phone: "+2348102345678",
      email: "contact@ironhavenfit.com",
      website: "https://ironhavenfit.com",
    },
    verification: {
      status: "PENDING",
      documents: {
        gymPhotos: ["https://example.com/gym1.jpg"],
        cacDocs: ["https://example.com/cac1.jpg"],
        ninOrId: ["https://example.com/nin1.jpg"],
        ownerIdCard: ["https://example.com/owner1.jpg"],
        bankAccount: {
          bankName: "GTBank",
          accountNumber: "1234567890",
          accountName: "Iron Haven Fitness",
        },
      },
    },
    amenities: [
      "Cardio Machines",
      "Weightlifting Area",
      "Personal Training",
      "Locker Rooms",
      "Showers",
    ],
    pricing: {
      daily: 1000,
      weekly: 5000,
      monthly: 15000,
      yearly: 60000,
    },
    openingHours: {
      "Mon-Fri": "5am - 10pm",
      Sat: "6am - 8pm",
      Sun: "6am - 6pm",
    },
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_2",
    ownerId: "user_2",
    name: "Pulse Active Gym",
    logoUrl: "https://example.com/logo2.jpg",
    description: "A modern gym with state-of-the-art equipment and classes.",
    location: {
      street: "45 Aba Road",
      city: "Port Harcourt",
      landmark: "Near Shopping Mall",
      address: "45 Aba Road, Port Harcourt, Rivers",
      country: "Nigeria",
      state: "Rivers",
      postalCode: "500272",
      geoData: {
        lat: 4.8156,
        lng: 7.0498,
      },
    },
    contact: {
      phone: "+2348098765432",
      email: "info@pulseactive.ng",
      website: "https://pulseactive.ng",
    },
    verification: {
      status: "VERIFIED",
      documents: {
        gymPhotos: ["https://example.com/gym2.jpg"],
        cacDocs: ["https://example.com/cac2.jpg"],
        ninOrId: ["https://example.com/nin2.jpg"],
        ownerIdCard: ["https://example.com/owner2.jpg"],
        bankAccount: {
          bankName: "Access Bank",
          accountNumber: "0987654321",
          accountName: "Pulse Active Gym",
        },
      },
    },
    amenities: [
      "Spinning Studio",
      "Yoga Classes",
      "CrossFit Zone",
      "Steam Room",
      "Cafe",
    ],
    pricing: {
      daily: 1200,
      weekly: 6000,
      monthly: 18000,
      yearly: 170000,
    },
    openingHours: {
      "Mon-Fri": "5:30am - 11pm",
      Sat: "6am - 9pm",
      Sun: "6am - 8pm",
    },
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_3",
    ownerId: "user_3",
    name: "CoreFlex Gym & Spa",
    logoUrl: "https://example.com/logo3.jpg",
    description: "A premium gym and spa offering holistic wellness services.",
    location: {
      street: "8 Nsikak Eduok Avenue",
      city: "Uyo",
      landmark: "Opposite Central Park",
      address: "8 Nsikak Eduok Avenue, Uyo, Akwa Ibom",
      country: "Nigeria",
      state: "Akwa Ibom",
      postalCode: "520101",
      geoData: {
        lat: 5.038,
        lng: 7.917,
      },
    },
    contact: {
      phone: "+2347012345678",
      email: "support@coreflex.com",
      website: "https://coreflex.com",
    },
    verification: {
      status: "PENDING",
      documents: {
        gymPhotos: ["https://example.com/gym3.jpg"],
        cacDocs: ["https://example.com/cac3.jpg"],
        ninOrId: ["https://example.com/nin3.jpg"],
        ownerIdCard: ["https://example.com/owner3.jpg"],
        bankAccount: {
          bankName: "UBA",
          accountNumber: "5678901234",
          accountName: "CoreFlex Gym & Spa",
        },
      },
    },
    amenities: [
      "Pilates Studio",
      "Massage Therapy",
      "Swimming Pool",
      "Aerobics Classes",
      "Healthy Juice Bar",
    ],
    pricing: {
      daily: 1500,
      weekly: 7500,
      monthly: 20000,
      yearly: 200000,
    },
    openingHours: {
      "Mon-Fri": "5am - 9pm",
      Sat: "6am - 8pm",
      Sun: "7am - 7pm",
    },
    rating: 4.5,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_4",
    ownerId: "user_4",
    name: "Titanium Strength Hub",
    logoUrl: "https://example.com/logo4.jpg",
    description:
      "A specialized gym focused on strength training and conditioning.",
    location: {
      street: "31 Independence Avenue",
      city: "Abuja",
      landmark: "Near National Stadium",
      address: "31 Independence Avenue, Abuja, FCT",
      country: "Nigeria",
      state: "FCT",
      postalCode: "900211",
      geoData: {
        lat: 9.0765,
        lng: 7.3986,
      },
    },
    contact: {
      phone: "+2348035678910",
      email: "hello@titaniumhub.ng",
      website: "https://titaniumhub.ng",
    },
    verification: {
      status: "VERIFIED",
      documents: {
        gymPhotos: ["https://example.com/gym4.jpg"],
        cacDocs: ["https://example.com/cac4.jpg"],
        ninOrId: ["https://example.com/nin4.jpg"],
        ownerIdCard: ["https://example.com/owner4.jpg"],
        bankAccount: {
          bankName: "Zenith Bank",
          accountNumber: "1234567809",
          accountName: "Titanium Strength Hub",
        },
      },
    },
    amenities: [
      "Olympic Weightlifting Platforms",
      "HIIT Zone",
      "Nutrition Consulting",
      "Locker Rooms",
      "Sauna",
    ],
    pricing: {
      daily: 1800,
      weekly: 9000,
      monthly: 22000,
      yearly: 210000,
    },
    openingHours: {
      "Mon-Fri": "5am - 11pm",
      Sat: "6am - 9pm",
      Sun: "6am - 6pm",
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_5",
    ownerId: "user_5",
    name: "Elevate Fitness Studio",
    logoUrl: "https://example.com/logo5.jpg",
    description:
      "A boutique fitness studio specializing in group classes and personal training.",
    location: {
      street: "22 Marian Road",
      city: "Calabar",
      landmark: "Next to Central Market",
      address: "22 Marian Road, Calabar, Cross River",
      country: "Nigeria",
      state: "Cross River",
      postalCode: "540271",
      geoData: {
        lat: 4.9757,
        lng: 8.3417,
      },
    },
    contact: {
      phone: "+2348123456789",
      email: "info@elevatefit.com",
      website: "https://elevatefit.com",
    },
    verification: {
      status: "PENDING",
      documents: {
        gymPhotos: ["https://example.com/gym5.jpg"],
        cacDocs: ["https://example.com/cac5.jpg"],
        ninOrId: ["https://example.com/nin5.jpg"],
        ownerIdCard: ["https://example.com/owner5.jpg"],
        bankAccount: {
          bankName: "First Bank",
          accountNumber: "3456789012",
          accountName: "Elevate Fitness Studio",
        },
      },
    },
    amenities: [
      "Dance Studio",
      "Spin Classes",
      "Meditation Area",
      "Smoothie Bar",
      "Outdoor Training Space",
    ],
    pricing: {
      daily: 1200,
      weekly: 6000,
      monthly: 16000,
      yearly: 155000,
    },
    openingHours: {
      "Mon-Fri": "6am - 10pm",
      Sat: "6am - 8pm",
      Sun: "7am - 6pm",
    },
    rating: 4.4,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_6",
    ownerId: "user_6",
    name: "ProMotion Fitness",
    logoUrl: "https://example.com/logo6.jpg",
    description:
      "A comprehensive fitness center with a focus on functional training.",
    location: {
      street: "77 Ogui Road",
      city: "Enugu",
      landmark: "Beside City Mall",
      address: "77 Ogui Road, Enugu, Enugu",
      country: "Nigeria",
      state: "Enugu",
      postalCode: "400102",
      geoData: {
        lat: 6.4402,
        lng: 7.4943,
      },
    },
    contact: {
      phone: "+2347056789123",
      email: "contact@promotionfit.com",
      website: "https://promotionfit.com",
    },
    verification: {
      status: "VERIFIED",
      documents: {
        gymPhotos: ["https://example.com/gym6.jpg"],
        cacDocs: ["https://example.com/cac6.jpg"],
        ninOrId: ["https://example.com/nin6.jpg"],
        ownerIdCard: ["https://example.com/owner6.jpg"],
        bankAccount: {
          bankName: "Fidelity Bank",
          accountNumber: "6789012345",
          accountName: "ProMotion Fitness",
        },
      },
    },
    amenities: [
      "CrossFit",
      "TRX Training",
      "Indoor Cycling",
      "Nutrition Bar",
      "Steam Room",
    ],
    pricing: {
      daily: 1300,
      weekly: 6500,
      monthly: 17000,
      yearly: 175000,
    },
    openingHours: {
      "Mon-Fri": "5am - 10pm",
      Sat: "6am - 9pm",
      Sun: "6am - 6pm",
    },
    rating: 4.3,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_7",
    ownerId: "user_7",
    name: "Arena Max Gym",
    logoUrl: "https://example.com/logo7.jpg",
    description: "A sports-focused gym with specialized training for athletes.",
    location: {
      street: "15 Challenge Road",
      city: "Ibadan",
      landmark: "Near University Campus",
      address: "15 Challenge Road, Ibadan, Oyo",
      country: "Nigeria",
      state: "Oyo",
      postalCode: "200283",
      geoData: {
        lat: 7.3775,
        lng: 3.947,
      },
    },
    contact: {
      phone: "+2347065432198",
      email: "arena@maxgym.com",
      website: "https://maxgym.com",
    },
    verification: {
      status: "PENDING",
      documents: {
        gymPhotos: ["https://example.com/gym7.jpg"],
        cacDocs: ["https://example.com/cac7.jpg"],
        ninOrId: ["https://example.com/nin7.jpg"],
        ownerIdCard: ["https://example.com/owner7.jpg"],
        bankAccount: {
          bankName: "Sterling Bank",
          accountNumber: "9012345678",
          accountName: "Arena Max Gym",
        },
      },
    },
    amenities: [
      "Boxing Ring",
      "Martial Arts Studio",
      "Treadmills",
      "Weightlifting Area",
      "Spa",
    ],
    pricing: {
      daily: 1100,
      weekly: 5500,
      monthly: 15000,
      yearly: 150000,
    },
    openingHours: {
      "Mon-Fri": "5am - 9pm",
      Sat: "6am - 8pm",
      Sun: "6am - 6pm",
    },
    rating: 4.2,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_8",
    ownerId: "user_8",
    name: "Velocity Performance Center",
    logoUrl: "https://example.com/logo8.jpg",
    description:
      "A high-performance training center for serious athletes and fitness enthusiasts.",
    location: {
      street: "33A Aminu Kano Crescent",
      city: "Abuja",
      landmark: "Opposite Central Park",
      address: "33A Aminu Kano Crescent, Abuja, FCT",
      country: "Nigeria",
      state: "FCT",
      postalCode: "900108",
      geoData: {
        lat: 9.082,
        lng: 7.491,
      },
    },
    contact: {
      phone: "+2348023456789",
      email: "support@velocitycenter.ng",
      website: "https://velocitycenter.ng",
    },
    verification: {
      status: "VERIFIED",
      documents: {
        gymPhotos: ["https://example.com/gym8.jpg"],
        cacDocs: ["https://example.com/cac8.jpg"],
        ninOrId: ["https://example.com/nin8.jpg"],
        ownerIdCard: ["https://example.com/owner8.jpg"],
        bankAccount: {
          bankName: "Union Bank",
          accountNumber: "2345678901",
          accountName: "Velocity Performance Center",
        },
      },
    },
    amenities: [
      "Functional Training",
      "Olympic Lifting Platforms",
      "Sports Rehab",
      "Physiotherapy",
      "Cafe",
    ],
    pricing: {
      daily: 2000,
      weekly: 10000,
      monthly: 25000,
      yearly: 250000,
    },
    openingHours: {
      "Mon-Fri": "5am - 10pm",
      Sat: "6am - 9pm",
      Sun: "7am - 6pm",
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_9",
    ownerId: "user_9",
    name: "Zenith Wellness Gym",
    logoUrl: "https://example.com/logo9.jpg",
    description:
      "A holistic wellness center combining fitness and mindfulness practices.",
    location: {
      street: "19 Nnebisi Road",
      city: "Asaba",
      landmark: "Near Government House",
      address: "19 Nnebisi Road, Asaba, Delta",
      country: "Nigeria",
      state: "Delta",
      postalCode: "320242",
      geoData: {
        lat: 6.198,
        lng: 6.7285,
      },
    },
    contact: {
      phone: "+2348034567890",
      email: "contact@zenithwellness.com",
      website: "https://zenithwellness.com",
    },
    verification: {
      status: "PENDING",
      documents: {
        gymPhotos: ["https://example.com/gym9.jpg"],
        cacDocs: ["https://example.com/cac9.jpg"],
        ninOrId: ["https://example.com/nin9.jpg"],
        ownerIdCard: ["https://example.com/owner9.jpg"],
        bankAccount: {
          bankName: "Wema Bank",
          accountNumber: "4567890123",
          accountName: "Zenith Wellness Gym",
        },
      },
    },
    amenities: [
      "Yoga Studio",
      "Pilates",
      "Cardio Zone",
      "Nutrition Coaching",
      "Sauna",
    ],
    pricing: {
      daily: 1000,
      weekly: 5000,
      monthly: 14000,
      yearly: 135000,
    },
    openingHours: {
      "Mon-Fri": "6am - 9pm",
      Sat: "6am - 8pm",
      Sun: "6am - 6pm",
    },
    rating: 4.1,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "gym_10",
    ownerId: "user_10",
    name: "PowerHouse Athletics",
    logoUrl: "https://example.com/logo10.jpg",
    description:
      "A comprehensive athletic training facility for all fitness levels.",
    location: {
      street: "101 Stadium Road",
      city: "Benin City",
      landmark: "Adjacent to Sports Complex",
      address: "101 Stadium Road, Benin City, Edo",
      country: "Nigeria",
      state: "Edo",
      postalCode: "300251",
      geoData: {
        lat: 6.335,
        lng: 5.6037,
      },
    },
    contact: {
      phone: "+2348091234567",
      email: "power@houseathletics.com",
      website: "https://houseathletics.com",
    },
    verification: {
      status: "VERIFIED",
      documents: {
        gymPhotos: ["https://example.com/gym10.jpg"],
        cacDocs: ["https://example.com/cac10.jpg"],
        ninOrId: ["https://example.com/nin10.jpg"],
        ownerIdCard: ["https://example.com/owner10.jpg"],
        bankAccount: {
          bankName: "Ecobank",
          accountNumber: "7890123456",
          accountName: "PowerHouse Athletics",
        },
      },
    },
    amenities: [
      "Basketball Court",
      "Strength Training",
      "Cardio Zone",
      "Spa",
      "Juice Bar",
    ],
    pricing: {
      daily: 1400,
      weekly: 7000,
      monthly: 19000,
      yearly: 185000,
    },
    openingHours: {
      "Mon-Fri": "5am - 10pm",
      Sat: "6am - 9pm",
      Sun: "6am - 7pm",
    },
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
